#!/bin/bash
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --gpus-per-node=2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=04:00:00
#SBATCH --job-name=train_linear
#SBATCH --output=./output/%x-%j.out

# entire script fails if a single command fails
set -e

module purge
module load 2023
module load Anaconda3/2023.07-2

PROJECT_DIR="$PWD"
ENV_PREFIX="$PROJECT_DIR"/.env

source activate $ENV_PREFIX

python -c "import torch; print('CUDA available:', torch.cuda.is_available()); print('CUDA device count:', torch.cuda.device_count()); print('CUDA device name:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'No CUDA device')"

python attacker_to_LLM.py --data_type train --sentence_aggregation linear --batch_size 64 --num_epochs 1
