#!/bin/bash 
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --gpus-per-node=1
#SBATCH --job-name=InteractiveSession
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=01:30:00
#SBATCH --output=./logs/interactive-session-%A.out

# entire script fails if a single command fails
set -e

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.4.0

PROJECT_DIR="$PWD"
ENV_PREFIX="$PROJECT_DIR"/.env

source activate $ENV_PREFIX

mkdir -p ~/.config/code-server

export CODE_SERVER_CONFIG=~/.config/code-server/config_interactive.yaml
node=$(/bin/hostname)
port=10121
user=${USER} 

if [ -f ${CODE_SERVER_CONFIG} ] ; then
 rm ${CODE_SERVER_CONFIG}
fi

echo "bind-addr: ${node}:${port}" >> $CODE_SERVER_CONFIG 
echo "auth: password" >> $CODE_SERVER_CONFIG
echo "password: qwerty1234!" >> $CODE_SERVER_CONFIG
echo "cert: false" >> $CODE_SERVER_CONFIG

echo "Copy the following line in a new terminal to create a secure SSH tunnel between your computer and Snellius compute node."
echo "ssh -L localhost:${port}:${node}:${port} ${user}@snellius.surf.nl"

code-server --auth=password