#!/bin/bash 
#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --gpus-per-node=1
#SBATCH --job-name=run_masking
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=02:30:00
#SBATCH --output=./logs/run_masking-%A.out

# entire script fails if a single command fails
set -e

module purge
module load 2023
module load Anaconda3/2023.07-2
module load CUDA/12.4.0

PROJECT_DIR="$PWD"
ENV_PREFIX="$PROJECT_DIR"/.env

source activate $ENV_PREFIX

python LLM_expert_masking.py